// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUoWzHTJpmyEH5wxcLrD298DDzCtpAq-E',
    appId: '1:22414908830:web:8fb97e456453a3335f4a8f',
    messagingSenderId: '22414908830',
    projectId: 'macs-fhsu',
    authDomain: 'macs-fhsu.firebaseapp.com',
    storageBucket: 'macs-fhsu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgRSe4M1scOFIUFvDNuNAm4Z20uqhkDgA',
    appId: '1:22414908830:android:91ca5c93e593775e5f4a8f',
    messagingSenderId: '22414908830',
    projectId: 'macs-fhsu',
    storageBucket: 'macs-fhsu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHZsbEAGHrfZaqc_Y5c4kj2IBBkWyskYc',
    appId: '1:22414908830:ios:42ca42acf73c499d5f4a8f',
    messagingSenderId: '22414908830',
    projectId: 'macs-fhsu',
    storageBucket: 'macs-fhsu.firebasestorage.app',
    iosBundleId: 'com.example.simpleAttendanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHZsbEAGHrfZaqc_Y5c4kj2IBBkWyskYc',
    appId: '1:22414908830:ios:42ca42acf73c499d5f4a8f',
    messagingSenderId: '22414908830',
    projectId: 'macs-fhsu',
    storageBucket: 'macs-fhsu.firebasestorage.app',
    iosBundleId: 'com.example.simpleAttendanceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUoWzHTJpmyEH5wxcLrD298DDzCtpAq-E',
    appId: '1:22414908830:web:9f4117fda2613bb05f4a8f',
    messagingSenderId: '22414908830',
    projectId: 'macs-fhsu',
    authDomain: 'macs-fhsu.firebaseapp.com',
    storageBucket: 'macs-fhsu.firebasestorage.app',
  );

}